name: antassistant
description: –
publish_to: 'none'
version: 1.1.0+4

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.1
  http: ^0.13.5
  flutter_secure_storage: ^7.0.1
  either_dart: ^0.3.0
  html: ^0.15.1
  url_launcher: ^6.1.7
  dynamic_color: ^1.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.11.0

flutter_icons:
  android: true
  ios: true
  image_path: "icon/antassistant-icon.png"
  image_path_android: "icon/antassistant-icon-foreground.png"

flutter:
  uses-material-design: true
